name: ${project.name}
main: org.morganm.logores.LogOresPlugin
url: ${project.url}
version: ${project.version}
author: morganm
database: true
softdepend: [Vault, WorldEdit, Permissions, PermissionsEx]
commands:
  lo:
    description: Log ores admin functions
    usage: /<command>
